name: sim-network

topology:
  defaults:
    kind: linux
  
  nodes:
    r1:
      image: alpine-frr:latest
      binds:
        # ルーターの場合は、初期設定用のディレクトリをマウント
        - /home/junkreef/network-simulator/backend/src/app/configs/r1/daemons:/etc/frr/daemons:ro
        - /home/junkreef/network-simulator/backend/src/app/configs/r1/frr.conf:/etc/frr/frr.conf.import:ro
        - /home/junkreef/network-simulator/backend/src/app/configs/r1/vtysh.conf:/etc/frr/vtysh.conf:ro
      exec:
        # 起動後にインターフェース設定等を適用するための初期化コマンド
        - ip link set dev eth1 up || true
    t1:
      image: alpine-terminal:latest
      exec:
        # 起動後にインターフェース設定等を適用するための初期化コマンド
        - ip link set dev eth1 up || true

  links:
    - endpoints:
      - "r1:eth1"
      - "t1:eth1"
